SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/key.pem"

# Power saving by skipping signature validation on boot (still validated on update)
SB_CONFIG_BEE_BOOT_SKIP_SIGNATURE_VALIDATION=y
